export { default as Authentication } from "./authentication/index";
export { default as Settings } from "./settings";
export { default as Navbar } from "./navbar";
export { default as Posts } from "./Posts/index";
export { default as HomePage } from "./HomePage/index";
export { default as CreatePost } from "./CreatePost";
export { default as UserProfile } from "./UserProfile";
export { default as Chat } from "./chat";
export { default as People } from "./people";
